name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Update composer (1/2)
      run: composer update --ignore-platform-req=ext-fileinfo
    - name: Update composer (2/2)
      run: composer install --ignore-platform-req=ext-fileinfo
    - name: Starting project (1/2)
      run: php artisan serve
    - name: Starting project (2/2)
      run: npm run dev
